import React from 'react'

const PrivacyPolicy = () => {
  return (
    <>
      <section className="about-hero">
        <h1 className="about-hero-title">
          <span className="about-hero-highlight">Privacy Policy</span>
        </h1>
      </section>

      <section className="section-padding min-h-[50vh]">
        <div className="max-w-[1000px] mx-auto px-5 text-[#555] space-y-6 leading-relaxed">
          <p className="font-bold text-[#1a1a2e]">Last updated: December 11, 2024</p>
          <p>
            No mobile information will be shared with third parties or affiliates for marketing or promotional purposes. All the categories mentioned above exclude text messaging originator opt-in data and consent, which will not be shared with any third parties.
          </p>
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h2 className="text-2xl font-bold text-[#1a1a2e] mt-8 mb-4">Interpretation</h2>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h2 className="text-2xl font-bold text-[#1a1a2e] mt-8 mb-4">Definitions</h2>
          <p>For the purposes of this Privacy Policy:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Best Merchant Services, 21550 W Oxnard St #630, Woodland Hills, CA 91367, United States.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: California, United States</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>Website</strong> refers to Best Merchant Services, accessible from https://bestmerchantservices.com/</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1a1a2e] mt-8 mb-4">Personal Data</h2>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
          </ul>

          <h2 className="text-2xl font-bold text-[#1a1a2e] mt-8 mb-4">Usage Data</h2>
          <p>
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>
          
          <h2 className="text-2xl font-bold text-[#1a1a2e] mt-8 mb-4">Tracking Technologies and Cookies</h2>
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
          </p>
          <p>
            For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
          </p>

          <h2 className="text-2xl font-bold text-[#1a1a2e] mt-8 mb-4">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul className="list-disc pl-5 space-y-2">
            <li>By visiting this page on our website: <a href="/contact-us" className="text-[#1b53e0] hover:underline">Contact Us</a></li>
            <li>By phone number: <a href="tel:8003831553" className="text-[#1b53e0] hover:underline">(800) 383-1553</a></li>
          </ul>
        </div>
      </section>
    </>
  )
}

export default PrivacyPolicy
